export const SOURCE_AGENT = 'Agent Source';
export const SOURCE_VERIFIER = 'Verificateur Source';
export const SOURCE_STRUCTURE = 'Structure Source';
export const LOCAL_INFORMER = 'Informateur Local';
export const NATIONAL_INFORMER = 'Informateur National';
export const LOCAL_VERIFIER = 'Verificateur Local';
export const aerodromeRoles = [SOURCE_AGENT, SOURCE_STRUCTURE, SOURCE_VERIFIER];
export const localInformerRoles = [LOCAL_INFORMER, LOCAL_VERIFIER];
export const nationalInformerRoles = [NATIONAL_INFORMER];
